### ISSUE TITLE
Unable to download amphorae file

### ISSUE THREAD

**Issue by rob-yerc** [amphoradata/amphora#3]
I am looking my amphorae for CSIRO Soil Property Data for Latitude 34.1 to 34.2 S and Longitude 140.5 to 140.6 E.  I click on files and it lists the 3 files.  When I click on Download, it appears to be working but no file is downloaded and it just brings me back to the Amphorae details page

---

⚠ Do not edit this section. It is required for amphoradata.com ➟ GitHub issue linking.
* AmphoraId: 522881c2-8c66-4ed5-8ca7-705cb528146c

**Comment by xtellurian** [comment]
The files in question are actually empty (i.e. they are zero bytes), hence why the download appears to be failing.

I'm going to add a feature in 0.6.4 to show a more useful error when this occurs.

**Comment by xtellurian** [comment]
@DrDonDon can you look into why those files are empty?

**Comment by xtellurian** [comment]
This amphora has been deleted.
